### ISSUE TITLE
Probably my ineptitude, but: No package 'harfbuzz' found

### ISSUE THREAD

**Issue by IntelSgt** [albinoz/ffmpeg-static-OSX#10]
[Compile_Log.txt](https://github.com/albinoz/ffmpeg-static-OSX/files/5504383/Compile_Log.txt)

**Comment by albinoz** [comment]
Hi, Thanks for repport,
Yes the new libass 0.15 was out just after my script update,
You can just use libass 0.14 version to fix this,
Xvid also ask user now,
I work to patch all and more add soon.
This issue will close when update done ;)

**Comment by albinoz** [comment]
Hi,
Update available,
Have Fun
