### ISSUE TITLE
RTMP?

### ISSUE THREAD

**Issue by HamptonMakes** [albinoz/ffmpeg-static-OSX#11]
Hi-

 Just found this project as I'm trying to get my clean static build of ffmpeg for Mac... any chance of getting librtmp included?

**Comment by albinoz** [comment]
Hi,

No, it is not include for now,
I will try to add it

**Comment by albinoz** [comment]
I was cheat for add librtmp what hard to build ( require specific openssl version & patch etc… )
Let me know if it work like you wish
Have a Nice Day !

**Comment by HamptonMakes** [comment]
wow! thanks!
