### ISSUE TITLE
get an updated bzip2

### ISSUE THREAD

**Issue by Kori-San** [albinoz/ffmpeg-static-OSX#12]
Hi, with this code you can get an updated version of bzip2 release : 

#_ bzip
tput bold ; echo ; echo '📍 ' bzip2 - Git ; tput sgr0 ; sleep 2
cd ${CMPL}
git clone git://sourceware.org/git/bzip2.git bzip2
cd bzip2
make -j "$THREADS" && make install PREFIX=${TARGET}
rm -fr ${CMPL}/*

**Comment by albinoz** [comment]
Thanks for purpose, Added ;)
