### ISSUE TITLE
Apple Silicon version?

### ISSUE THREAD

**Issue by stefcarlens** [albinoz/ffmpeg-static-OSX#13]
Any plans for an Apple Silicon version?
It is already possible because I saw site offering static FFmpeg builds for AS.

**Comment by albinoz** [comment]
Hi,
For moment many binaries not ready to support AS,
the site offering support AS no build all binaries supported in ffmpeg-static-OSX at this time,
but yes I will see if I can build optimised build for AS with a Mac mini at my work,
please be patient, for now ffmpeg-static-OSX support MacOS 11 on Mac mini AS but with Rosetta.

Best regards

**Comment by stefcarlens** [comment]
I am afraid you are late to the party. Several sites already offer ARM FFmpeg builds for AS.
Even one offers builds that use ARM NEON optimisations which makes it very fast.
Just check out www.osxexperts.net

**Comment by albinoz** [comment]
It's better to contribute more in code than in comments,
take to your own time to do it if you cannot survive.
Breath and wait ;)
