### ISSUE TITLE
line 306: /Volumes/Ramdisk/compile/libogg-1.3.4/c8fca6b4a02d695b1ceea39b330d4406001c03ed.patch?full_index=1: No such file or directory

### ISSUE THREAD

**Issue by IntelSgt** [albinoz/ffmpeg-static-OSX#16]
[adam-FFmpeg-Static.log](https://github.com/albinoz/ffmpeg-static-OSX/files/6736863/adam-FFmpeg-Static.log)

**Comment by albinoz** [comment]
Hi, Thanks for repport,
I look this

**Comment by albinoz** [comment]
Fixed ;)
Have a nice Day

**Comment by IntelSgt** [comment]
Thank you! Works for me too!

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
