### ISSUE TITLE
libzimg

### ISSUE THREAD

**Issue by stefcarlens** [albinoz/ffmpeg-static-OSX#17]
It would be great if libzimg is added to this script. This is needed for getting the new ZScale to work.

Here is the source https://github.com/sekrit-twc/zimg but I have little knowledge how to add this.

**Comment by albinoz** [comment]
Hi,
Thanks for suggest,
I will try to add it

**Comment by albinoz** [comment]
Hi Again,
Added ;)
Have a nice Day !
