### ISSUE TITLE
"dyld: Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib"

### ISSUE THREAD

**Issue by Wowfunhappy** [albinoz/ffmpeg-static-OSX#3]
Hello!

I was able to successfully compile ffmpeg via this script. However, when I move my compiled ffmpeg binary to a fresh machine, I get the error in the issue title: `dyld: Library not loaded: /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib`

The binary does work on the machine it was compiled on, but if it needs this non-OS-supplied library, it's not really static. Can this be worked around?

(General note: I find that often with these types of errors, there's actually more than one library missing, but you won't get the error about the next one until you correct the first...)

**Comment by albinoz** [comment]
Hi Sorry for the late,

You need to uninstall all libSDL if you want ffmpeg-static-OSX script not include it during build,
and with "normaly" succes build with no dependency with sdl

Let me know if work without sdl2
