### ISSUE TITLE
libass not found using pkg-config

### ISSUE THREAD

**Issue by ushan** [albinoz/ffmpeg-static-OSX#4]
I get "**libass not found using pkg-config**"
it happens with other libs which are installed using **"make install"** but not with **brew**
I tried to add such strings
```
export LD_LIBRARY_PATH="/Volumes/Ramdisk/sw/lib/"
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:"/Volumes/Ramdisk/sw/lib/pkgconfig"
export PKG_CONFIG_LIBDIR=$PKG_CONFIG_LIBDIR:"/Volumes/Ramdisk/sw/lib/"
```

but it doesn't help

As I understand to make it working next command 
pkg-config --libs --cflags libass
should get a valid path after "make install" (like "/Volumes/Ramdisk/sw/lib/libass"
but it returns:

`Package libass was not found in the pkg-config search path.`

`unlike pkg-config --libs --cflags libpng`

_$ pkg-config --libs --cflags libpng
-I/usr/local/Cellar/libpng/1.6.37/include/libpng16 -L/usr/local/Cellar/libpng/1.6.37/lib -lpng16 -lz_

**Comment by albinoz** [comment]
I recommend to uninstall the pkg-config installed with "make install"  for the good path found.
Your installed pkg-config with "make install" is used rather the ffmpeg-static-OSX builded one
Some binaries from manual, brew or other install could break the build,
your libpng look installed from brew,
try a brew list and suppress it

**Comment by ushan** [comment]
Thank you so much for answering!
It really helped!
I disabled this string
https://github.com/albinoz/ffmpeg-static-OSX/blob/master/ffmpeg-static-OSX.command#L104
and called:
```
cd /Volumes/Ramdisk/compile/pkg-config-0.29.2/
make uninstall
```
I am not sure which one made it fixed I am figuring out, but thank you for the script and for your help
