### ISSUE TITLE
Hardened runtime

### ISSUE THREAD

**Issue by onmyway133** [albinoz/ffmpeg-static-OSX#5]
Hi, thanks for the script. I also tried some other prebuilt static binary, but in order to notarize we need to resign with hardened runtime enabled

After `codesign --verbose --force -o runtime --sign`, the ffmpeg and ffprobe breaks, it says can't detect audio codec. Do you have any idea how to make it work with hardened runtime?

**Comment by albinoz** [comment]
Hi,

I have no idea why this broke ffmpeg,
I found this over google maybe help you

http://swati-ios.blogspot.com/2017/01/ffmpeg-binary-in-osx-package.html
